### ISSUE TITLE
not booting properly 

### ISSUE THREAD

**Issue by MagnusJune** [justaPancakeGuy/esp32CaptivePortalRickroll#1]
Ordered all the things you listed In your video, connected everything identical, and in the Arduino IDE Serial Monitor I'm just getting a "SD card initialization failed" and it doesn't broadcast a wifi network either. 

Any Help would be appreciated. 

this is what the serial monitor outputs on boot up. 

23:39:40.848 -> ets Jul 29 2019 12:21:46
23:39:40.848 -> 
23:39:40.848 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
23:39:40.881 -> configsip: 0, SPIWP:0xee
23:39:40.882 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
23:39:40.882 -> mode:DIO, clock div:1
23:39:40.882 -> load:0x3fff0030,len:4832
23:39:40.882 -> load:0x40078000,len:16460
23:39:40.882 -> load:0x40080400,len:4
23:39:40.882 -> load:0x40080404,len:3504
23:39:40.882 -> entry 0x400805cc
23:39:41.838 -> SD card initialization failed

**Comment by justaPancakeGuy** [comment]
Is the card formatted to fat32?

**Comment by MagnusJune** [comment]
Yeah, 16GB micro SD card, formatted to Fat32

**Comment by justaPancakeGuy** [comment]
@MagnusJune Ok try rewiring the whole thing just to double check and if that dousnt work try following this tutorial https://www.electronicwings.com/esp32/microsd-card-interfacing-with-esp32

**Comment by justaPancakeGuy** [comment]
@MagnusJune did it work?

**Comment by MagnusJune** [comment]
It did not.. 
I’ve moved over to using a raspberry pi zero 2 W instead for myself, and got it going with some ChatGPT code .
